name: Build VSCode SysMon
on: 
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      # Prepare Job
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Create Release Semver
      - name: Generate Semantic Version
        id: semver
        uses: rapidstack/PR-Label-Semver-Action@v1.3.6
        with:
          default_bump: patch

      # Set Project Version
      - name: Set Frontend Version
        run: npm version ${{ steps.semver.outputs.string }}
