name: Build VSCode SysMon
on: 
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      # Prepare Job
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Create Release Semver
      - name: Generate Semantic Version
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Set Project Version
      - name: Set Frontend Version
        run: npm version ${{ steps.semver.outputs.tag }}
