name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
jobs:
  check_labels:
    - name: Check Semver Labels
      runs-on: ubuntu-latest
      steps:
        - uses: docker://agilepathway/pull-request-label-checker:latest
          with:
            one_of: major,minor,patch
            repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Release Labels
      runs-on: ubuntu-latest
      steps:
        - uses: docker://agilepathway/pull-request-label-checker:latest
          with:
            one_of: breaking-change,bug,dependency,documentation,enhancement,skip-changelog,wontfix
            repo_token: ${{ secrets.GITHUB_TOKEN }}